# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: ''
  DOTNET_MULTILEVEL_LOOKUP: 0

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Pack
      run: dotnet pack
    - name: Tag
      run: git tag My-First-Release-5 && git push --tags --force
    - name: GitHub release
      uses: Smaug123/gr-common-actions/github-release@e80e601862cc4c7a2f8ff35fabf1d22f65c1c1c0
      with:
        tag: My-First-Release-5
        github-token: ${{ secrets.GITHUB_TOKEN }}
