# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: ''
  DOTNET_MULTILEVEL_LOOKUP: 0

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      attestations: write
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Pack
      run: dotnet pack
    - name: Locate nupkg
      id: locate-nupkg
      run: echo "output=$(find . -type f -name '*.nupkg')" > $GITHUB_OUTPUT
    - name: Release
      uses: G-Research/common-actions/github-release@f416691f43413cc4e625b9b980fabc8bdeaf901f
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        target-commitish: ${{ github.sha }}
        tag: test-tag
        binary-contents: ${{ steps.locate-nupkg.outputs.output }}
