# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: ''
  DOTNET_MULTILEVEL_LOOKUP: 0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # If generate-release-notes is true then you must pass `target-commitish`. This is apparently undocumented.
        generate: [true, false]
        tag-exists: [true, false]
        explicit-commitish: ["${{ github.event.pull_request.head.sha }}", ""]

    permissions:
      contents: write
      actions: write

    steps:
    - uses: actions/checkout@v4
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Pack
      run: dotnet pack
    - name: Tag
      id: tag
      env:
        TAG_EXISTS: ${{ matrix.tag-exists }}
      run: |
        TAG_NAME=$(basename $(mktemp -t tmp.XXXXXXXX))
        if [[ "$TAG_EXISTS" = "true" ]]; then
          git tag "$TAG_NAME" && git push --tags --force
        fi
        echo "tag=$TAG_NAME" >> "$GITHUB_OUTPUT"

    - name: GitHub release
      if: ${{ matrix.generate == false || matrix.explicit-commitish }}
      uses: Smaug123/gr-common-actions/github-release@6ddb72cc82101f343017ec040a1a1f53fbb91d6d
      with:
        tag: ${{ steps.tag.outputs.tag }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        target-commitish: ${{ matrix.explicit-commitish }}
        generate-release-notes: ${{ matrix.generate }}
