# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: ''
  DOTNET_MULTILEVEL_LOOKUP: 0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # If generate-release-notes is true then you must pass `target-commitish`. This is apparently undocumented.
        generate: [false]
        tag-exists: [false]
        explicit-commitish: ["${{ github.event.pull_request.head.sha }}"]

    permissions:
      id-token: write
      attestations: write
      contents: write
      actions: write

    steps:
    - uses: actions/checkout@v4
    - name: Restore dependencies
      if: always()
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Pack
      run: dotnet pack
    - name: Tag
      id: tag
      env:
        TAG_EXISTS: ${{ matrix.tag-exists }}
      run: |
        TAG_NAME=$(basename $(mktemp -t tmp.XXXXXXXX))
        if [[ "$TAG_EXISTS" = "true" ]]; then
          git tag "$TAG_NAME" && git push --tags --force
        fi
        echo "tag=$TAG_NAME" >> "$GITHUB_OUTPUT"

    - name: GitHub release
      if: ${{ matrix.generate == false || matrix.explicit-commitish }}
      uses: Smaug123/gr-common-actions/github-release@18d687eacc2581b591f131f5bae9f941fa30f37b
      with:
        tag: ${{ steps.tag.outputs.tag }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        target-commitish: ${{ matrix.explicit-commitish }}
        generate-release-notes: ${{ matrix.generate }}

    - name: Create GitHub attestation
      uses: actions/attest-build-provenance@897ed5eab6ed058a474202017ada7f40bfa52940 # v1.0.0 
      with:
        subject-path: "Lib.fs"

    - name: Create bundle
      id: attestation-bundle
      run: |
        ATT_OUTPUT="/tmp/attestation-Lib.fs"
        GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
        gh attestation download Lib.fs -R "${{ github.repository }}" > "$ATT_OUTPUT"
        echo "outfile=$ATT_OUTPUT" >> "$GITHUB_OUTPUT"

    - name: Release attestation
      uses: Smaug123/gr-common-actions/github-release@6ddb72cc82101f343017ec040a1a1f53fbb91d6d
      with:
        tag: ${{ steps.tag.outputs.tag }}
        target-commitish: ${{ matrix.explicit-commitish }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        generate-release-notes: false
        binary_contents: ${{ steps.attestation-bundle.outputs.outfile }}
